name: Ensure Development Branch Exists

on:
  workflow_dispatch:

jobs:
  ensure-dev-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Ensure development branch exists
        run: |
          if [[ "${{ steps.branch-names.outputs.current_branch }}" != "development" && ! git show-ref --verify --quiet refs/heads/development ]]; then
            git checkout -b development
            git push origin development
          fi

      - name: Trigger Create Feature Branch Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-feature-branch.yml/dispatches \
            -d '{"ref":"main"}'
