name: Create Development Branch On Repo Init

on:
  create:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git user identity
        run: |
          git config --global user.email "javis@github.com"
          git config --global user.name "Javis Ghost Actions"

      - name: Check if development branch exists
        run: |
          if ! git show-ref --verify --quiet refs/heads/development; then
            echo "Development branch does not exist. Creating..."
            git checkout -b development
            git commit --allow-empty -m "Initial commit"
            git push origin development
          else
            echo "Development branch already exists."
          fi

      - name: Pull latest changes from main
        run: |
          git pull origin main

      - name: Push changes to development branch
        run: |
          git checkout -b development
          git push origin development
