# This is a basic workflow to help you get started with Actions

name: Create Development Branch On Repo Init

# Controls when the workflow will run
on:
  create:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Pull latest changes from main
        run: git pull origin main

      - name: Create development branch
        run: |
          git checkout -b development
          git push origin development
