name: Create Development Branch On Repo Init

on:
  create:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git user identity
        run: |
          git config --global user.email "kiwanukamarvin579.com"
          git config --global user.name "kaggwe-marvin"

      - name: Initialize repository with initial commit
        run: |
          git commit --allow-empty -m "Initial commit"
          git push origin main

      - name: Pull latest changes from main
        run: |
          git pull origin main

      - name: Create development branch
        run: |
          git checkout -b development
          git push origin development
