name: Create Development Branch On Repo Init

on:
  create:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git user identity
        run: |
          git config --global user.email "javis@github.com"
          git config --global user.name "Javis GitHub Actions"

      - name: Check if main branch exists
        run: |
          if ! git show-ref --verify --quiet refs/heads/main; then
            echo "Main branch does not exist. Creating..."
            git checkout -b main
            git config pull.rebase false
            git pull origin main
            git push origin main
          else
            echo "Main branch already exists."
          fi

      - name: Initialize repository with initial commit
        run: |
          git checkout -b development
          git commit --allow-empty -m "Initial commit"
          git push origin development

      - name: Pull latest changes from main
        run: |
          git pull origin main

      - name: Create development branch
        run: |
          git checkout -b development
          git push origin development
