# try again
name: Create Development Branch On Repo Init

on:
  create:
    branches:
      - main

jobs:
  setup-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set Git user identity
        run: |
          git config --global user.email "kiwanukamarvin597@gmail.com"
          git config --global user.name "saybaba"

      - name: Create development branch if it does not exist
        run: |
          if ! git show-ref --verify --quiet refs/heads/development; then
            git checkout -b development
            git push origin development:development
          else
            echo ":: Development branch already exists."
          fi

      - name: Checkout development branch
        run: |
          git checkout development

      - name: Create feature branch from development branch
        run: |
          git checkout -b feature/setup-branch development
          
      - name: Touch create_branch.sh and set permissions
        run: |
          touch create_branch.sh
          chmod +x create_branch.sh

      - name: Generate create_branch.sh content
        run: |
          echo '#!/bin/bash' > create_branch.sh
          echo 'create_branch() {' >> create_branch.sh
          echo 'local prefix="${prefix}/${name}"' >> create_branch.sh
          echo 'if ! git show-ref --verify --quiet refs/heads/development; then' >> create_branch.sh
          echo 'echo ":: Development branch does not exist. Exiting."' >> create_branch.sh
          echo 'exit 1' >> create_branch.sh
          echo 'fi' >> create_branch.sh
          echo 'git checkout development' >> create_branch.sh
          echo 'git pull origin development' >> create_branch.sh
          echo 'git checkout -b "$branch_name"' >> create_branch.sh
          echo 'git push -u origin "$branch_name"' >> create_branch.sh
          echo 'echo ":: Branch '''$branch_name''' created and pushed to remote."' >> create_branch.sh
          echo '}' >> create_branch.sh
          echo 'if [ "$#" -ne 1 ]; then' >> create_branch.sh
          echo 'echo ":: Usage: $0 [feature|bugfix]"' >> create_branch.sh
          echo 'exit 1' >> create_branch.sh
          echo 'fi' >> create_branch.sh
          echo 'type=$1' >> create_branch.sh
          echo 'echo ":: Enter the branch name:"' >> create_branch.sh
          echo 'read name' >> create_branch.sh
          echo 'create_branch "$type" "$name"' >> create_branch.sh

      - name: Commit and push feature branch
        run: |
          git add create_branch.sh
          git commit -m "Add create_branch.sh"
          git push origin feature/setup-branch
