name: Create Development Branch On Repo Init

on:
  create:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git user identity
        run: |
          git config --global user.email "javis@github.com"
          git config --global user.name "Javis Ghost Actions"

      - name: Check if development branch exists
        run: |
            git checkout -b development
            git commit --allow-empty -m "Initial commit"
            git pull origin development
            git push origin development
            echo "Development branch already exists."
         
