# on create
name: Create Development Branch On Repo Init

on:
  create:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest changes from main
        run: |
          git pull origin main

      - name: Create development branch
        run: |
          git checkout -b development
          git push origin development
