name: Create Development Branch On Repo Init

on:
  create:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git user identity
        run: |
          git config --global user.email "kiwanukamarvin597@gmail.com"
          git config --global user.name "saybaba"

      - name: Create development branch
        run: |
          if ! git show-ref --verify --quiet refs/heads/development; then
            echo "Creating development branch..."
            git checkout -b development
            git push origin development
            echo "Development branch created successfully"
          else
            echo "Development branch already exists."
          fi
