name: Feature and Bugfix Branch Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

permissions:
  pull-requests: write
  checks: write
  contents: read
  issues: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable persisting GITHUB_TOKEN to avoid using it for authentication
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use SSH key for authentication

      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Create Pull Request
        id: create-pr
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git checkout -b ${{ steps.branch-names.outputs.current_branch }}
          git push origin ${{ steps.branch-names.outputs.current_branch }}
          hub pull-request -b development -m "New ${{ steps.branch-names.outputs.current_branch }}: ${{ github.event.head_ref }}" -h ${{ steps.branch-names.outputs.current_branch }} -o "${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
