name: Feature and Bugfix Branch Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

permissions:
  pull-requests: write
  checks: write
  contents: read
  issues: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable persisting GITHUB_TOKEN to avoid using it for authentication
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use SSH key for authentication

      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6.0.5
        with:
          commit-message: "New ${steps.branch-names.outputs.current_branch}: ${{ github.event.head_ref }}"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          branch: "${{ steps.branch-names.outputs.current_branch }}"
          delete-branch: true
          base: "development"
          title: "${{ steps.branch-names.outputs.current_branch }}: ${{ github.event.head_ref }}"
          body: "This pull request is automatically generated for the ${{ steps.branch-names.outputs.current_branch }} branch."
          labels: "${{ steps.branch-names.outputs.current_branch }}"
          draft: false
      
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.AUTO_PR_BOT }}
      
      - name: Check outputs
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
      